server:
  port: 8080


bs:
  mysql:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/account_service_db?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: password
    pool:
      name: order-mysql