server:
  port: 8080


bs:
  mysql:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.142.159.154:3306/account_service_db?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: ordermatching
    password: Team3$
    pool:
      name: order-mysql